config/routes.rb
Rails.application.routes.draw do

  resources :comments
  resources :comments
  resources :comments
scope :teachercenter, as: :teacenter do
    get '/' => 'teachercenter#index'
    get 'courses' => 'teachercenter#courses'
    get 'comments' => 'teachercenter#comments'
    get 'messages' => 'teachercenter#messages'
    get 'course/new' => 'teachercenter#new_course'
    get 'courses/:course_id' => 'teachercenter#course', as: :course
    post 'course/create' => 'teachercenter#create_course'
    post 'revise' => 'teachercenter#revise'
    post 'dispose/course' => 'teachercenter#dispose_course'
end

  scope :usercenter, as: :ucenter do
      get '/' => 'usercenter#index'
      get 'courses' => 'usercenter#courses'
      get 'course/:course_id' => 'usercenter#course', as: :course
      get 'comments' => 'usercenter#comments'
      get 'messages' => 'usercenter#messages'
      get 'more' => 'usercenter#more'
      post 'revise' => 'usercenter#revise'
  end

  get 'login' => 'main#login', as: :login
  get 'register' => 'main#register', as: :register
  post 'login' => 'accounts#login'
  post 'register' => 'accounts#register'
  delete 'logout' => 'accounts#logout', as: :logout
  get 'students/:id/courses' => 'students#courses', as: :student_courses
  get 'students/:id/courses/:course_id' => 'students#course', as: :student_course
  get 'teachers/:teacher_id/courses/new' => 'courses#new', as: :appoint

  post 'courses/:id/entry' => 'courses#entry', as: :entry_course
  post 'courses/create' => 'courses#create', as: :create_course

  resources :courses do

  end

  resources :accounts do
  end
  resources :teachers
  resources :students

  root 'main#index'

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
      @students = Student.order(created_at: :desc).limit(5)
      @teachers = Teacher.order(created_at: :desc).limit(8)
      @courses = Course.where(is_public: true).order(created_at: :desc).limit(4)
      if session[:user_id]
        @account = Account.find(session[:user_id])
      else
        @account = Account.new
      end
  end
  def login
  end
  def logout
      session[:user_id] = nil
  end
  def register
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/_courses.html.erb
<div class='box-header'>
  <h2>Courses</h2>
  <%= link_to courses_path, class: ['more'] do%>
    <span class='glyphicon glyphicon-th-list'></span>
  <% end %>
</div>
<div class='box-body'>
  <ul class='collection'>
    <% if !@courses.nil? %>
      <% @courses.each do |course| %>
        <li class='list-item course'>
          <div class='sign'></div>
          <%= link_to course_path(course), class: :ico do %>
            <%=  image_tag 'index/avatar.jpg' %>
          <% end %>
          <div class='information'>
            <span><%= link_to course.score %></span>
            <p><%= course.name %></p>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/main/_flowshow.html.erb
<ul class='collection' role='label-container'>
  <li class='item' role='flow-label'>
    <a class='btn btn-primary' href='#'>131</a>
  </li>
  <li class="item" role='flow-label'>
    <a class='btn btn-default' href='#'>adad</a>
  </li>
  <li class="item" role='flow-label'>
    <a class='btn btn-success' href='#'>33</a>
  </li>
  <li class="item" role='flow-label'>
    <a class='btn btn-danger' href='#'>ada</a>
  </li>
  <li class="item" role='flow-label'>
    <a class='btn btn-info' href='#'>f322</a>
  </li>
  <li class="item" role='flow-label'>
    <a class='btn btn-warning' href='#'>23rwd</a>
  </li>
  <li class="item" role='flow-label'>
    <a class='btn btn-primary' href='#'>;d;a</a>
  </li>
  <li class="item" role='flow-label'>
    <a class='btn btn-success' href='#'>11q</a>
  </li>
  <li class='item' role='flow-label'>
    <a class='btn btn-primary' href='#'>131</a>
  </li>
  <li class="item" role='flow-label'>
    <a class='btn btn-default' href='#'>adad</a>
  </li>
  <li class="item" role='flow-label'>
    <a class='btn btn-success' href='#'>33</a>
  </li>
  <li class="item" role='flow-label'>
    <a class='btn btn-danger' href='#'>ada</a>
  </li>
  <li class="item" role='flow-label'>
    <a class='btn btn-info' href='#'>f322</a>
  </li>
  <li class="item" role='flow-label'>
    <a class='btn btn-warning' href='#'>23rwd</a>
  </li>
  <li class="item" role='flow-label'>
    <a class='btn btn-primary' href='#'>;d;a</a>
  </li>
  <li class="item" role='flow-label'>
    <a class='btn btn-success' href='#'>11q</a>
  </li>
  <li class='item' role='flow-label'>
    <a class='btn btn-primary' href='#'>131</a>
  </li>
  <li class="item" role='flow-label'>
    <a class='btn btn-default' href='#'>adad</a>
  </li>
  <li class="item" role='flow-label'>
    <a class='btn btn-success' href='#'>33</a>
  </li>
  <li class="item" role='flow-label'>
    <a class='btn btn-danger' href='#'>ada</a>
  </li>
  <li class="item" role='flow-label'>
    <a class='btn btn-info' href='#'>f322</a>
  </li>
  <li class="item" role='flow-label'>
    <a class='btn btn-warning' href='#'>23rwd</a>
  </li>
  <li class="item" role='flow-label'>
    <a class='btn btn-primary' href='#'>;d;a</a>
  </li>
  <li class="item" role='flow-label'>
    <a class='btn btn-success' href='#'>11q</a>
  </li>
  <li class="item" role='flow-label'>
    <a class='btn btn-info' href='#'>f322</a>
  </li>
  <li class="item" role='flow-label'>
    <a class='btn btn-warning' href='#'>23rwd</a>
  </li>
  <li class="item" role='flow-label'>
    <a class='btn btn-primary' href='#'>;d;a</a>
  </li>
  <li class="item" role='flow-label'>
    <a class='btn btn-success' href='#'>11q</a>
  </li>
  <li class='item' role='flow-label'>
    <a class='btn btn-primary' href='#'>131</a>
  </li>
  <li class="item" role='flow-label'>
    <a class='btn btn-default' href='#'>adad</a>
  </li>
  <li class="item" role='flow-label'>
    <a class='btn btn-success' href='#'>33</a>
  </li>
  <li class="item" role='flow-label'>
    <a class='btn btn-danger' href='#'>ada</a>
  </li>
  <li class="item" role='flow-label'>
    <a class='btn btn-info' href='#'>f322</a>
  </li>
  <li class="item" role='flow-label'>
    <a class='btn btn-warning' href='#'>23rwd</a>
  </li>
  <li class="item" role='flow-label'>
    <a class='btn btn-primary' href='#'>;d;a</a>
  </li>
  <li class="item" role='flow-label'>
    <a class='btn btn-success' href='#'>11q</a>
  </li>
</ul>

app/views/main/_informs.html.erb
<div class='panel' id='panel-1'>
  <div class='header'>HEADERE</div>
  <div class='body'>
    <ul>
      <li>ABCD</li>
      <li>ABCD</li>
      <li>ABCD</li>
      <li>ABCD</li>
      <li>ABCD</li>
    </ul>
  </div>
</div>
<div class='panel' id='panel-2'>
  <div class='header'>HEADERE</div>
  <div class='body'>
    <ul>
      <li>EFGH</li>
      <li>EFGH</li>
      <li>EFGH</li>
      <li>EFGH</li>
      <li>EFGH</li>
    </ul>
  </div>
</div>
<div class='panel' id='panel-3'>
  <div class='header'>HEADERE</div>
  <div class='body'>
    <ul>
      <li>HIJK</li>
      <li>HIJK</li>
      <li>HIJK</li>
      <li>HIJK</li>
      <li>HIJK</li>
    </ul>
  </div>
</div>

app/views/main/_sercher.html.erb
<div class='condition-group'>
	<button class="btn btn-default condition-header" id="condition-header-1">
	  搜索
	  <span class="caret"></span>
	</button>
	<div class="options-menu condition-menu" role="menu" id='condition-menu-1' expand='false'>
		<div id='condition-1' class='father-condition'>
			<label>ABC</label>
			<div class='clearfix'>
				<ul class='all-condition'><li class='all-item condition-item'>ALL</li></ul>
				<ul class='son-condition'>
					<li class='condition-item'>adhjada</li>
					<li class='condition-item'>adhjada</li>
					<li class='condition-item'>adhjada</li>
					<li class='condition-item'>adhjada</li>
					<li class='condition-item'>adhjada</li>
					<li class='condition-item'>adhjada</li>
					<li class='condition-item'>adhjada</li>
					<li class='condition-item'>adhjada</li>
					<li class='condition-item'>adhjada</li>
					<li class='condition-item'>adhjada</li>
					<li class='condition-item'>adhjada</li>
					<li class='condition-item'>adhjada</li>
					<li class='condition-item'>adhjada</li>
					<li class='condition-item'>adhjada</li>
					<li class='condition-item'>adhjada</li>
					<li class='condition-item'>adhjada</li>
				</ul>
			</div>
		</div>

		<div id='condition-2' class='father-condition'>
			<label>ABC</label>
			<div class='clearfix'>
				<ul class='all-condition'><li class='all-item condition-item'>ALL</li></ul>
				<ul class='son-condition'>
					<li class='condition-item'>adhjada</li>
					<li class='condition-item'>adhjada</li>
					<li class='condition-item'>adhjada</li>
					<li class='condition-item'>adhjada</li>
					<li class='condition-item'>adhjada</li>
					<li class='condition-item'>adhjada</li>
					<li class='condition-item'>adhjada</li>
					<li class='condition-item'>adhjada</li>
					<li class='condition-item'>adhjada</li>
					<li class='condition-item'>adhjada</li>
					<li class='condition-item'>adhjada</li>
					<li class='condition-item'>adhjada</li>
					<li class='condition-item'>adhjada</li>
					<li class='condition-item'>adhjada</li>
					<li class='condition-item'>adhjada</li>
					<li class='condition-item'>adhjada</li>
				</ul>
			</div>
		</div>

	</div>
</div>

app/views/main/_students.html.erb
<div class='box-header'>
  <h2>Students</h2>
  <%= link_to students_path, class: ['more'] do%>
    <span class='glyphicon glyphicon-th-list'></span>
  <% end %>
</div>
<div class='box-body'>
  <table class='table'>
    <thead>
      <tr class='tr'>
        <td class='td'>Name</td>
        <td class='td'>sex</td>
        <td class='td'>address</td>
        <td class='td'>subject</td>
      </tr>
    </thead>
    <tbody class='students-collection'>
      <% if !@students.nil? %>
        <% @students.each do |student| %>
          <tr class='vertical-middle students-list'>
            <td><%= student.name%></td>
            <td><%= student.sex%></td>
            <td><%= student.address%></td>
            <td><%= student.school%></td>
            <td><%= student.account.nil? %></td>
            <td><%= link_to 'View', student, class: ['btn btn-sm btn-primary']%></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/main/_teachers.html.erb
<div class='box-header'>
  <h2>Teachers</h2>
  <%= link_to teachers_path, class: ['more'] do%>
    <span class='glyphicon glyphicon-th-list'></span>
  <% end %>
</div>
<div class='box-body'>
  <ul class='collection'>
    <% if !@teachers.nil? %>
      <% @teachers.each do |teacher| %>
        <li class='list-item teacher'>
          <div class='sign'></div>
          <%= link_to teacher_path(teacher), class: :ico do %>
            <%=  image_tag 'index/avatar.jpg' %>
          <% end %>
          <div class='information'><%= teacher.id %></div>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/main/login.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_tag "/login", method: "post" do %>
      <div class='field'>
        <%= label_tag :account_num, 'account' %>
        <%= text_field_tag(:acount_num) %>
      </div>
      <div class='field'>
        <%= label_tag :password, 'password' %>
        <%= password_field_tag (:pwd) %>
      </div>
      <%= submit_tag "Sign in", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/main/logout.html.erb
<%= link_to 'Logout',logout_path, action: :logout,method: :delete%>

app/views/main/register.html.erb
Error: Source sample is missing.