config/routes.rb
Rails.application.routes.draw do

  resources :comments
  resources :comments
  resources :comments
scope :teachercenter, as: :teacenter do
    get '/' => 'teachercenter#index'
    get 'courses' => 'teachercenter#courses'
    get 'comments' => 'teachercenter#comments'
    get 'messages' => 'teachercenter#messages'
    get 'course/new' => 'teachercenter#new_course'
    get 'courses/:course_id' => 'teachercenter#course', as: :course
    post 'course/create' => 'teachercenter#create_course'
    post 'revise' => 'teachercenter#revise'
    post 'dispose/course' => 'teachercenter#dispose_course'
end

  scope :usercenter, as: :ucenter do
      get '/' => 'usercenter#index'
      get 'courses' => 'usercenter#courses'
      get 'course/:course_id' => 'usercenter#course', as: :course
      get 'comments' => 'usercenter#comments'
      get 'messages' => 'usercenter#messages'
      get 'more' => 'usercenter#more'
      post 'revise' => 'usercenter#revise'
  end

  get 'login' => 'main#login', as: :login
  get 'register' => 'main#register', as: :register
  post 'login' => 'accounts#login'
  post 'register' => 'accounts#register'
  delete 'logout' => 'accounts#logout', as: :logout
  get 'students/:id/courses' => 'students#courses', as: :student_courses
  get 'students/:id/courses/:course_id' => 'students#course', as: :student_course
  get 'teachers/:teacher_id/courses/new' => 'courses#new', as: :appoint

  post 'courses/:id/entry' => 'courses#entry', as: :entry_course
  post 'courses/create' => 'courses#create', as: :create_course

  resources :courses do

  end

  resources :accounts do
  end
  resources :teachers
  resources :students

  root 'main#index'

end

app/controllers/usercenter_controller.rb
class UsercenterController < ApplicationController
  before_action :set_current, :check_login

  def index
  end

  def courses
      set_student
      @nonpaged_courses = @student.courses
      @courses = @nonpaged_courses.page(params[:page]).per(10)
  end

  def course
      @course = courses.find(params[:course_id])
      @comment = Comment.find_by(student_id: @account.student, course_id: @course) || Comment.new
  end

  def comments
      set_student
      @nonpaged_comments = @student.comments
      @comments = @nonpaged_comments.page(params[:page]).per(10)
  end

  def messages

  end

  def more
  end

  def revise
    respond_to do |format|
      if @account.student.update(revise_params)
        format.json { render :revise }
      else
        format.json { render :revise }
      end
    end
  end

  private

  def set_current
       @current = params[:action]
  end
  def account_params
    #
    params.require(:revise).permit()
  end
  def revise_params
      {params[:revise].keys.first => params[:revise].values.first}
  end
end

app/helpers/usercenter_helper.rb
module UsercenterHelper
end

app/views/usercenter/_menu_tab.html.erb
<div id='usercenter-tab' class='user-info-tab tab'>
  <ul>
    <li class="tab-list <%= check_current 'index'%>"><%= link_to'基本信息', ucenter_path %></li>
    <li class="tab-list <%= check_current 'courses'%>"><%= link_to '我的课程', ucenter_courses_path %></li>
    <li class="tab-list <%= check_current 'comments'%>"><%= link_to '我的评价', ucenter_comments_path %></li>
    <li class="tab-list <%= check_current 'messages'%>"><%= link_to '我的消息', ucenter_messages_path %></li>
    <li class="tab-list <%= check_current 'more'%>"><%= link_to '更多', ucenter_more_path %></li>
  </ul>
  <% if !@account.teacher %>
    <div class='fix-right'><%= link_to '申请当教师', new_teacher_path, class: 'btn btn-success' %></div>
  <% end %>
</div>

app/views/usercenter/comments.html.erb
<%= render 'menu_tab' %>
<div class='info-box fix-bounds'>
  <table class='table'>
    <thead>
      <tr class='tr'>
        <td class='td'>课程</td>
        <td class='td'>教师</td>
        <td class='td'>评级</td>
        <td class='td'>综合评分</td>
        <td class='td'>评论时间</td>
        <td></td>
      </tr>
    </thead>
    <tbody class='collection'>
      <% if !@comments.nil? %>
        <% @comments.each do |c| %>
          <tr class='vertical-middle students-list'>
            <td><%= c.course.name %></td>
            <td><%= c.course.teacher.name || c.course.teacher.account.number  %></td>
            <td><%= c.mark %></td>
            <td>
              <% $i = 0 %>
              <% $i += 1 if c.manner %>
              <% $i += 1 if c.level %>
              <% $i += 1 if c.pattern %>
              <% $i = 1 if $i == 0 %>
              <%= format("%0.2f",((c.manner || 0) + (c.level || 0) + (c.pattern || 0)).to_f / $i) %>分
				</td>
            <td><%= c.updated_at.nil? ? c.updated_at.strftime("%Y-%m-%d") : c.created_at.strftime("%Y-%m-%d")  %></td>
            <td><%= link_to '详情', comment_path(c), class: ['btn btn-sm btn-primary']%></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <%= paginate @comments %>
</div>

app/views/usercenter/course.html.erb
<p id="notice"><%= notice %></p>
<% if notice.nil? %>
  <button class='back btn btn-sm btn-primary' role='back'>Back</button>
<% else %>
  <button class='back btn btn-sm btn-primary' role='back double'>Back</button>
<% end %>
<div class='course-info'>
  <div class='info-box'>
    <div class='ico-box'>
      <%=  image_tag 'index/avatar.jpg', class: ['info-ico'] %>
      <br>
      <span class='label label-success'><%= set_course_stage @course.stage %></span>
    </div>
    <ul class='fix-ico-right'>
      <li class='fix-item'>
        <span>课程名：</span>
        <span><%= @course.name%></span>
      </li>
      <li class='fix-item'>
        <span>讲师：</span>
        <span><%= link_to @course.teacher.name || @course.teacher.account.number, @course.teacher %></span>
      </li>
      <li class='fix-item'>
        <span>课程类型：</span>
        <span><%= @course.category %></span>
      </li>
      <li class='fix-item'>
        <span>开班日期:</span>
        <span><%= @course.begintime %></span>
      </li>
      <li class='fix-item'>
        <span>地点:</span>
        <span><%= @course.place %></span>
      </li>
      <li class='fix-item'>
        <span>上课时间:</span>
        <span><%= @course.class_time %></span>
      </li>
      <li class='fix-item'>
        <span>课时数:</span>
        <span><%= @course.is_public %></span>
      </li>
      <li class='fix-item'>
        <span>课程评分:</span>
        <span><%= @course.score %></span>
      </li>
      <li class='fix-item'>
        <span>价格:</span>
        <span><%= @course.price %></span>
      </li>
    </ul>
  </div>
</div>
<div class='intro-box'>
  <div class='intro-head'>
    <span>课程介绍</span>
  </div>
  <div class='intro-content'>
    <span><%= @course.intro %>假装是课程介绍</span>
  </div>
</div>
<% if @course.stage == 'finished' %>
  <% if !@comment.id.nil? %>
    <div class='comment-box'>
      <div class='comment-head'>
        <p>我的评价</p>
        <a class='label btn-info' data-toggle='modal' , data-target='#comment'>修改评价</a>
      </div>
      <div class='comment-content'>
        <div class='fix-left'>
          <div class="field">
            <span>教学态度</span>
            <div class='stars'>
              <% if  @comment.manner.nil? %>
                未评星
                <% else %>
                <% $i = 1 %>
                <% while $i <= 5 do %>
                  <span class='glyphicon<%= $i <= @comment.manner ? ' glyphicon-star' : ' glyphicon-star-empty'%> '></span>
                  <% $i+= 1 %>
                <% end %>
              <% end %>
            </div>
          </div>
          <div class="field">
            <span>教学水平</span>
            <div class='stars'>
              <% if  @comment.level.nil? %>
                未评星
                <% else %>
                <% $i = 1 %>
                <% while $i <= 5 do %>
                  <span class='glyphicon<%= $i <= @comment.level ? ' glyphicon-star' : ' glyphicon-star-empty'%> '></span>
                  <% $i+= 1 %>
                <% end %>
              <% end %>
            </div>
          </div>
          <div class="field">
            <span>授课方式</span>
            <div class='stars'>
              <% if  @comment.pattern.nil? %>
                未评星
                <% else %>
                <% $i = 1 %>
                <% while $i <= 5 do %>
                  <span class='glyphicon<%= $i <= @comment.pattern ? ' glyphicon-star' : ' glyphicon-star-empty'%> '></span>
                  <% $i+= 1 %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
        <div class='contents'>
          <span><%= @comment.content%></span>
        </div>
      </div>
    </div>
  <% end %>
  <% if @comment.id.nil? %>
    <button data-toggle='modal' , data-target='#comment' class='btn btn-success'>评价</button>
  <% end %>
  <% if @course.is_public %>
<div class='info-box'>
  <h4>课程评价</h4>
  <table class='table'>
    <thead>
      <tr class='tr'>
        <td class='td'>学生</td>
        <td class='td'>评级</td>
        <td class='td'>综合评分</td>
        <td class='td'>评论时间</td>
        <td></td>
      </tr>
    </thead>
    <tbody class='collection'>
      <% if @course.comments.length == 0 %>
        <tr>
          <td>暂无评价</td>
        </tr>
      <% else%>
        <% @course.comments.each do |c| %>
          <tr class='vertical-middle students-list'>
            <td><%= c.student.name || c.student.account.number  %></td>
            <td><%= c.mark %></td>
            <td>
              <% $i = 0 %>
              <% $i += 1 if c.manner %>
              <% $i += 1 if c.level %>
              <% $i += 1 if c.pattern %>
              <% $i = 1 if $i == 0 %>
              <%= format("%0.2f",((c.manner || 0) + (c.level || 0) + (c.pattern || 0)).to_f / $i) %>分
          </td>
            <td><%= c.updated_at || c.created_at %></td>
            <td><%= link_to '详情', comment_path(c), class: ['btn btn-sm btn-primary']%></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>
<% end %>
<div class="modal fade" id="comment" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">Close</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">评论</h4>
      </div>
      <div class="modal-body">
        <%= form_for @comment do |f|%>
          <%= f.hidden_field :course_id, value: @course.id %>
          <div class='form-body'>
            <div class='fix-center'>
              <div class="field">
                <%= f.label :mark %>
                <%= f.hidden_field :mark %>
                <div class='mark-star'>
                  <span class='glyphicon glyphicon-star-empty' role='mark'></span>
                  <span class='glyphicon glyphicon-star-empty' role='mark'></span>
                  <span class='glyphicon glyphicon-star-empty' role='mark'></span>
                  <span class='glyphicon glyphicon-star-empty' role='mark'></span>
                  <span class='glyphicon glyphicon-star-empty' role='mark'></span>
                </div>
              </div>
              <div class="field">
                <%= f.label :manner %>
                <%= f.hidden_field :manner %>
                <div class='mark-star'>
                  <span class='glyphicon glyphicon-star-empty' role='mark'></span>
                  <span class='glyphicon glyphicon-star-empty' role='mark'></span>
                  <span class='glyphicon glyphicon-star-empty' role='mark'></span>
                  <span class='glyphicon glyphicon-star-empty' role='mark'></span>
                  <span class='glyphicon glyphicon-star-empty' role='mark'></span>
                </div>
              </div>
              <div class="field">
                <%= f.label :level %>
                <%= f.hidden_field :level %>
                <div class='mark-star'>
                  <span class='glyphicon glyphicon-star-empty' role='mark'></span>
                  <span class='glyphicon glyphicon-star-empty' role='mark'></span>
                  <span class='glyphicon glyphicon-star-empty' role='mark'></span>
                  <span class='glyphicon glyphicon-star-empty' role='mark'></span>
                  <span class='glyphicon glyphicon-star-empty' role='mark'></span>
                </div>
              </div>
              <div class="field">
                <%= f.label :pattern %>
                <%= f.hidden_field :pattern %>
                <div class='mark-star'>
                  <span class='glyphicon glyphicon-star-empty' role='mark'></span>
                  <span class='glyphicon glyphicon-star-empty' role='mark'></span>
                  <span class='glyphicon glyphicon-star-empty' role='mark'></span>
                  <span class='glyphicon glyphicon-star-empty' role='mark'></span>
                  <span class='glyphicon glyphicon-star-empty' role='mark'></span>
                </div>
              </div>
            </div>
            <div class="field">
              <textarea name="comment[content]" placeholder="请输入评论"></textarea>
            </div>
          </br>
          <div class='form-footer'>
            <div class="actions">
              <button class="btn btn-danger" data-dismiss='modal'>取消</button>
              <button class='btn btn-primary' type="submit">提交</button>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<% elsif @course.stage == 'ongoing' %>
  <label class='label label-danger'>Tips:完成课程后即可进行评价</label>
<% end %>

app/views/usercenter/courses.html.erb
<%= render 'menu_tab' %>
<div class='courses_panel fix-bounds'>
  <div class='course_tab'>
    <ul id='course-tab' role="tablist">
      <li role="presentation" class="active">
        <a href="#all" role="tab" data-toggle="tab">全部课程</a>
      </li>
      <li role="presentation">
        <a href='#ongoing' role="tab" data-toggle="tab">进行中</a>
      </li>
      <li role="presentation">
        <a href='#finished' role="tab" data-toggle="tab">已结课</a>
      </li>
    </ul>
  </div>
  <div class='tab-content course-content'>
    <% stage = Array['all', 'waiting', 'ongoing', 'finished'] %>
    <% stage.each do |s| %>
      <table id='<%= s %>' class="table tab-pane<%= ' active' if s == 'all' %>" role="tabpanel">
        <thead>
          <tr>
            <td>课程名：</td>
            <td>教师：</td>
            <td>学科：</td>
            <td>状态：</td>
            <td></td>
          </tr>
        </thead>
        <tbody>
          <% if !@courses.nil? %>
            <% @courses.each do |c| %>
              <% if c.stage == s || s == 'all' %>
                <tr>
                  <td><%= c.name %></td>
                  <td><%= link_to c.teacher.name || c.teacher.account.number, teacher_path(c.teacher)%></td>
                  <td><%= c.category %></td>
                  <td><%= set_course_stage c.stage %></td>
                  <td><%= link_to '详情', ucenter_course_path(c), class: [:btn, 'btn-primary'] %></td>
                </tr>
              <% end %>
            <% end %>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
  <%= paginate @courses %>
</div>

app/views/usercenter/index.html.erb
<%= render 'menu_tab' %>
<div class='user-info'>
  <div class='info-box'>
    <div class='ico-box'>
      <%=  image_tag 'index/avatar.jpg', class: ['info-ico'] %>
      <a href='#' class='btn btn-primary btn-sm'>更换</a>
    </div>
    <ul class='fix-ico-right'>
      <li class='fix-item'>
        <span>帐号：</span>
        <span><%= @account.number %></span>
      </li>
      <li class='fix-item'>
        <span>会员状态：</span>
        <% if @account.is_vip %>
          <span>已开通</span>
          <a href='#' class='state-ture'>续费会员</a>
        <% else %>
          <span>暂未开通</span>
          <a href='#' class='state-false'>立即开通VIP</a>
        <% end %>
      </li>
    </ul>
  </div>
  <div class='phone-email info-box'>
    <div class='phone'>
      <div class='ico-box'><img src='<%= %>' class='info-ico'></div>
      <ul class='fix-ico-right'>
        <li class='fix-item'>
          <% if @account.phone %>
            <p>手机已验证</p>
            <span><%= @account.phone %></span>
            <a href='#' class='state-ture'>修改手机号</a>
          <% else %>
            <p>手机未绑定</p>
            <a href='#' class='state-false'>立即绑定</a>
          <% end %>
        </li>
      </ul>
    </div>
    <div class='email'>
      <div class='ico-box'><img src='' class='info-ico'></div>
      <ul class='fix-ico-right'>
        <li class='fix-item'>
          <% if @account.email %>
            <p>邮箱已验证</p>
            <span><%= @account.email %></span>
            <a href='#' class='state-ture'>修改邮箱</a>
          <% else %>
            <p>邮箱未绑定</p>
            <a href='#' class='state-false'>立即绑定</a>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>
<div class='detail-info'>
  <ul>
    <li class='info-item'>
      <span>姓名</span>
      <div role='info-cotent'>
        <em role='info' data-attr='name'><%= @account.student.name %></em>
        <input type='text-field' name='revise[name]' class='edit' role='edit'>
      </div>
      <div class='revise-group' role='revise-group'>
        <a class='revise' role='revise'>修改</a>
        <div class='control-group'>
          <a class='revise' role='cancel'>取消</a>
          <a class='revise' role='conform' data-target='usercenter/revise'>确定</a>
        </div>
      </div>
    </li>
    <li class='info-item'>
      <span>性别</span>
      <div role='info-cotent'>
        <em role='info' name='revise[sex]' data-attr='sex'><%= @account.student.sex %></em>
        <input type='text-field' name='revise[sex]' class='edit' role='edit'>
      </div>
      <div class='revise-group' role='revise-group'>
        <a class='revise' role='revise'>修改</a>
        <div class='control-group'>
          <a class='revise' role='cancel'>取消</a>
          <a class='revise' role='conform' data-target='usercenter/revise'>确定</a>
        </div>
      </div>
    </li>
    <li class='info-item'>
      <span>生日</span>
      <div role='info-cotent'>
        <em role='info' data-attr='bornday'><%= @account.student.bornday %></em>
        <input type='date' name='revise[bornday]' role='edit' class='edit'>
      </div>
      <div class='revise-group' role='revise-group'>
        <a class='revise' role='revise'>修改</a>
        <div class='control-group'>
          <a class='revise' role='cancel'>取消</a>
          <a class='revise' role='conform' data-target='usercenter/revise'>确定</a>
        </div>
      </div>
    </li>
    <li class='info-item'>
      <span>地址</span>
      <div role='info-cotent'>
        <em role='info' data-attr='address'><%= @account.student.address %></em>
        <input type='text-field' name='revise[address]' class='edit' role='edit'>
      </div>
      <div class='revise-group' role='revise-group'>
        <a class='revise' role='revise'>修改</a>
        <div class='control-group'>
          <a class='revise' role='cancel'>取消</a>
          <a class='revise' role='conform' data-target='usercenter/revise'>确定</a>
        </div>
      </div>
    </li>
    <li class='info-item'>
      <span>学校</span>
      <div role='info-cotent'>
        <em role='info' data-attr='school'><%= @account.student.school %></em>
        <input type='text-field' name='revise[school]' class='edit' role='edit'>
      </div>
      <div class='revise-group' role='revise-group'>
        <a class='revise' role='revise'>修改</a>
        <div class='control-group'>
          <a class='revise' role='cancel'>取消</a>
          <a class='revise' role='conform' data-target='usercenter/revise'>确定</a>
        </div>
      </div>
    </li>
    <li class='info-item'>
      <span>年级</span>
      <div role='info-cotent'>
        <em role='info' data-attr='grade'><%= @account.student.grade %></em>
        <input type='text-field' name='revise[grade]' class='edit' role='edit'>
      </div>
      <div class='revise-group' role='revise-group'>
        <a class='revise' role='revise'>修改</a>
        <div class='control-group'>
          <a class='revise' role='cancel'>取消</a>
          <a class='revise' role='conform' data-target='usercenter/revise'>确定</a>
        </div>
      </div>
    </li>
  </ul>
</div>
<div class='intro-box detail-info'>
  <div class='intro-head'>
    <span>自我介绍</span>
  </div>
  <div class='intro-content'>
    <div class='revise-group' role='revise-group'>
      <a class='revise' role='revise'>修改</a>
      <div class='control-group'>
        <a class='revise' role='cancel'>取消</a>
        <a class='revise' role='conform' data-target='usercenter/revise'>确定</a>
      </div>
    </div>
    <div role='info-cotent'>
      <em role='info' data-attr='intro'>
        <span><%= @account.student.intro %></span>
      </em>
      <textarea class='edit' name='revise[intro]' role='edit'><%= @account.student.intro %></textarea>
    </div>
  </div>
</div>

app/views/usercenter/messages.html.erb
<%= render 'menu_tab' %>
<div class='info-box fix-bounds'>
  <table class='table'>
    <thead>
      <tr class='tr'>
        <td class='td'>标题</td>
        <td class='td'>来自</td>
        <td class='td'>状态</td>
        <td class='td'>接收时间</td>
      </tr>
    </thead>
    <tbody class='collection'>
      <% if !@messages.nil? %>
        <% @messages.each do |m| %>
          <tr class='vertical-middle students-list'>
            <td><%= m.title %></td>
            <td><%= m.sender %></td>
            <td><%= m.isread %></td>
            <td><%= m.updated_at.nil? ? m.updated_at.strftime("%Y-%m-%d") : m.created_at.strftime("%Y-%m-%d")  %></td>
            <td><%= link_to '详情', teacenter_messages_path(m), class: ['btn btn-sm btn-primary']%></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/usercenter/more.html.erb
<%= render 'menu_tab' %>
<h1>Usercenter#more</h1>
<p>Find me in app/views/usercenter/more.html.erb</p>