config/routes.rb
Rails.application.routes.draw do

  resources :comments
  resources :comments
  resources :comments
scope :teachercenter, as: :teacenter do
    get '/' => 'teachercenter#index'
    get 'courses' => 'teachercenter#courses'
    get 'comments' => 'teachercenter#comments'
    get 'messages' => 'teachercenter#messages'
    get 'course/new' => 'teachercenter#new_course'
    get 'courses/:course_id' => 'teachercenter#course', as: :course
    post 'course/create' => 'teachercenter#create_course'
    post 'revise' => 'teachercenter#revise'
    post 'dispose/course' => 'teachercenter#dispose_course'
end

  scope :usercenter, as: :ucenter do
      get '/' => 'usercenter#index'
      get 'courses' => 'usercenter#courses'
      get 'course/:course_id' => 'usercenter#course', as: :course
      get 'comments' => 'usercenter#comments'
      get 'messages' => 'usercenter#messages'
      get 'more' => 'usercenter#more'
      post 'revise' => 'usercenter#revise'
  end

  get 'login' => 'main#login', as: :login
  get 'register' => 'main#register', as: :register
  post 'login' => 'accounts#login'
  post 'register' => 'accounts#register'
  delete 'logout' => 'accounts#logout', as: :logout
  get 'students/:id/courses' => 'students#courses', as: :student_courses
  get 'students/:id/courses/:course_id' => 'students#course', as: :student_course
  get 'teachers/:teacher_id/courses/new' => 'courses#new', as: :appoint

  post 'courses/:id/entry' => 'courses#entry', as: :entry_course
  post 'courses/create' => 'courses#create', as: :create_course

  resources :courses do

  end

  resources :accounts do
  end
  resources :teachers
  resources :students

  root 'main#index'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy, :entry]
  before_action :check_login, only: [:new, :create, :entry, :update]
  # layout 'collection'
  # GET /courses
  # GET /courses.json
  def index
    @nonpaged_courses = Course.where(is_public: true)
    @courses = @nonpaged_courses.page(params[:page]).per(16)
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    set_student
    set_teacher
  end

  # GET /courses/new
  def new
    @course = Course.new
    @teacher = Teacher.find(params[:teacher])
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)
    @course.is_public = false
    @teacher = Teacher.find(params[:course][:teacher_id])
    if @teacher == @account.teacher
       redirect_to  appoint_path(@teacher.id), notice: '预约失败！无法预约自己' and return
    end
    respond_to do |format|
      if @course.save && @teacher
        @account.student.courses << @course
        @teacher.courses << @course
        format.html { redirect_to ucenter_course_path(@course), notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, notice: '预约失败' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def entry
    set_student
    if !@course.is_public
        redirect_to course_path(@course), notice: '此课程非公开课，无法报名' and return
    elsif @account.teacher == @course.teacher
        redirect_to course_path(@course), notice: '不能报名自己开设的课程' and return
    elsif @student.courses.include?(@course)
        redirect_to ucenter_course_path(@course), notice: '您已报名过该课程，不能重复报名' and return
    end
    @student.courses << @course
    redirect_to ucenter_course_path(@course), notice: '报名成功！'
  end
  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find_by(id: params[:id], is_public: true)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :tutor, :category, :begintime, :endtime, :price, :place, :teacher_id)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<div class='form-panel'>
  <%= form_for(@course) do |f| %>
    <% if @course.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@course.errors.count, "error") %>
          prohibited this account from being saved:</h2>
        <ul>
          <% @course.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class='form-header'>
      <h2>请输入详细信息</h2>
    </div>
    <div class='form-body'>
      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :student_name %>
        <input type='text' name='student_name' value='<% @account.student.name %>'>
      </div>
      <div class="field">
        <%= f.label :category %>
        <%= f.text_field :category %>
      </div>
      <div class="field">
        <%= f.label :price %>
        <%= f.text_field :price %>
      </div>
      <div class="field">
        <%= f.label :place %>
        <%= f.text_field :place %>
      </div>
      <%= f.hidden_field 'teacher_id',value: @teacher.id %>
    </div>
    <div class='form-footer'>
      <div class="actions">
        <button class='btn' type="submit">提交</button>
      </div>
    </div>
  <% end %>
</div>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>
<%= render 'form' %>
<%= link_to 'Show', @course %>
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>
<button class='back btn btn-sm btn-primary' role='back'>Back</button>
<div class='fix-bounds'>
  <div class='box-header'>
    <h2>Courses</h2>
  </div>
  <%= render 'layouts/sercher' %>
  <div class='box-body fix-bounds'>
    <ul class='collection'>
      <% if !@courses.nil? %>
        <% @courses.each do |course| %>
          <li class='list-item course'>
            <div class='sign'></div>
            <%= link_to course_path(course), class: :ico do %>
              <%=  image_tag 'index/avatar.jpg' %>
            <% end %>
            <div class='information'>
              <span><%= link_to course.score %></span>
              <p><%= course.name %></p>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
    <div class='space-block'></div>
  </div>
  <%= paginate @courses %>
</div>

app/views/courses/new.html.erb
<p id="notice"><%= notice %></p>
<%= render 'form' %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>
<button class='back btn btn-sm btn-primary' role='back'>Back</button>
<div class='course-info'>
  <div class='info-box'>
    <div class='ico-box'>
      <%=  image_tag 'index/avatar.jpg', class: ['info-ico'] %>
    </div>
    <ul class='fix-ico-right'>
      <li class='fix-item'>
        <span>课程名：</span>
        <span><%= @course.name%></span>
      </li>
      <li class='fix-item'>
        <span>讲师：</span>
        <span><%= link_to @course.teacher.name || '', @course.teacher %></span>
      </li>
      <li class='fix-item'>
        <span>课程类型：</span>
        <span><%= @course.category %></span>
      </li>
      <li class='fix-item'>
        <span>开班日期:</span>
        <span><%= @course.begintime %></span>
      </li>
      <li class='fix-item'>
        <span>地点:</span>
        <span><%= @course.place %></span>
      </li>
      <li class='fix-item'>
        <span>上课时间:</span>
        <span><%= @course.class_time %></span>
      </li>
      <li class='fix-item'>
        <span>课时数:</span>
        <span><%= @course.is_public %></span>
      </li>
      <li class='fix-item'>
        <span>课程评分:</span>
        <span><%= @course.score %></span>
      </li>
      <li class='fix-item'>
        <span>价格:</span>
        <span><%= @course.price %></span>
      </li>
    </ul>
  </div>
</div>
<div class='intro-box'>
  <div class='intro-head'>
    <span>课程介绍</span>
  </div>
  <div class='intro-content'>
    <span><%= @course.intro %>假装是课程介绍</span>
  </div>
</div>
<!-- 帐号已登录且非该课程老师帐号的情况 -->
<% if @student && @teacher != @course.teacher %>
  <% if !@student.courses.include?(@course) &&%>
    <%= link_to '我要报名', entry_course_path(@course), method: :post, class: 'btn btn-primary'%>
  <% else %>
    <label class='label label-info'>您已报名该课程</label>
  <% end %>
  <!-- 帐号未登录的情况 -->
<% elsif !@student %>
  <%= link_to '我要报名', entry_course_path(@course), method: :post, class: 'btn btn-primary'%>
<% end %>