config/routes.rb
Rails.application.routes.draw do

  resources :comments
  resources :comments
  resources :comments
scope :teachercenter, as: :teacenter do
    get '/' => 'teachercenter#index'
    get 'courses' => 'teachercenter#courses'
    get 'comments' => 'teachercenter#comments'
    get 'messages' => 'teachercenter#messages'
    get 'course/new' => 'teachercenter#new_course'
    get 'courses/:course_id' => 'teachercenter#course', as: :course
    post 'course/create' => 'teachercenter#create_course'
    post 'revise' => 'teachercenter#revise'
    post 'dispose/course' => 'teachercenter#dispose_course'
end

  scope :usercenter, as: :ucenter do
      get '/' => 'usercenter#index'
      get 'courses' => 'usercenter#courses'
      get 'course/:course_id' => 'usercenter#course', as: :course
      get 'comments' => 'usercenter#comments'
      get 'messages' => 'usercenter#messages'
      get 'more' => 'usercenter#more'
      post 'revise' => 'usercenter#revise'
  end

  get 'login' => 'main#login', as: :login
  get 'register' => 'main#register', as: :register
  post 'login' => 'accounts#login'
  post 'register' => 'accounts#register'
  delete 'logout' => 'accounts#logout', as: :logout
  get 'students/:id/courses' => 'students#courses', as: :student_courses
  get 'students/:id/courses/:course_id' => 'students#course', as: :student_course
  get 'teachers/:teacher_id/courses/new' => 'courses#new', as: :appoint

  post 'courses/:id/entry' => 'courses#entry', as: :entry_course
  post 'courses/create' => 'courses#create', as: :create_course

  resources :courses do

  end

  resources :accounts do
  end
  resources :teachers
  resources :students

  root 'main#index'

end

app/controllers/teachercenter_controller.rb
class TeachercenterController < ApplicationController
    before_action :check_login
    before_action :set_teacher
    before_action :set_current
  def index
  end

  def courses
      @nonpaged_courses = @teacher.courses
      @courses = @nonpaged_courses.page(params[:page]).per(10)
  end

  def course
      @course = courses.find(params[:course_id])
  end

  def comments
      @nonpaged_comments = @teacher.comments
      @comments = @nonpaged_comments.page(params[:page]).per(10)
  end

  def messages

  end

  def revise
    respond_to do |format|
      if @teacher.update(revise_params)
        format.json { render :revise }
      else
        format.json { render :revise }
      end
    end
  end

  def course
    @course = courses.find(params[:course_id])
  end

  def new_course
    @course = Course.new
  end

  def create_course
    @course = Course.new(course_params)
    @course.is_public = true
    @course.stage = 'ongoing'
    respond_to do |format|
        if @course.save
          @teacher.courses << @course
          format.html { redirect_to ucenter_course_path(@course), notice: 'Course was successfully created.' }
          format.json { render :show, status: :created, location: @course }
        else
          format.html { render :new, notice: '创建失败！' }
        end
    end
  end

  def dispose_course
    @course = Course.find(params[:course_id])
    if @teacher.courses.include?(@course)
        if params[:command] == 'accept' && @course.stage == 'waiting'
            @course.update(stage: 'ongoing')
        elsif params[:command] == 'refuse' && @course.stage == 'waiting'
            @course.update(stage: 'refused')
        elsif params[:command] == 'finish' && @course.stage == 'ongoing'
            @course.update(stage: 'finished')
        end
        redirect_to teacenter_course_path(@course), notice: '操作成功！' and return
    end
    redirect_to teacenter_course_path(@course), notice: '操作无效！'
  end

  private

  def set_current
      @current = params[:action]
  end

  def course_params
    params.require(:course).permit(:name, :category, :begintime, :price, :place)
  end

  def revise_params
      {params[:revise].keys.first => params[:revise].values.first}
  end
end

app/helpers/teachercenter_helper.rb
module TeachercenterHelper
	def set_ele_id(type)
		if type == 'all'
			'all-courses'
		elsif type == 'true'
			'public-courses'
		elsif type == 'false'
			'private-courses'
		end
	end
end

app/views/teachercenter/_menu_tab.html.erb
<div id='usercenter-tab' class='user-info-tab tab'>
  <ul>
    <li class="tab-list <%= check_current 'index' %>"><%= link_to'教师信息', teacenter_path %></li>
    <li class="tab-list <%= check_current 'courses' %>"><%= link_to '课程管理', teacenter_courses_path %></li>
    <li class="tab-list <%= check_current 'comments' %>"><%= link_to '查看评价', teacenter_comments_path %></li>
    <li class="tab-list <%= check_current 'messages' %>"><%= link_to '我的消息', teacenter_messages_path %></li>
  </ul>
</div>
<%= yield %>

app/views/teachercenter/_teacher_tab.html.erb
	<div id='usercenter-tab' class='user-info-tab tab'>
	  <ul>
		  <li class='tab-list <%= check_current('index')%>'><%= link_to'教师信息', teacenter_path %></li>
		  <li class='tab-list <%= check_current('courses')%>'><%= link_to '课程管理', teacenter_courses_path %></li>
		  <li class='tab-list <%= check_current('students')%>'><%= link_to '学生管理', teacenter_students_path %></li>
		  <li class='tab-list <%= check_current('comments')%>'><%= link_to '查看评价', teacenter_comments_path %></li>
	  </ul>
   </div>

   <%= yield %>

app/views/teachercenter/comments.html.erb
<%= render 'menu_tab' %>
<div class='info-box fix-bounds'>
  <table class='table'>
    <thead>
      <tr class='tr'>
        <td class='td'>课程</td>
        <td class='td'>学生</td>
        <td class='td'>评级</td>
        <td class='td'>综合评分</td>
        <td class='td'>评论时间</td>
        <td></td>
      </tr>
    </thead>
    <tbody class='collection'>
      <% if !@comments.nil? %>
        <% @comments.each do |c| %>
          <tr class='vertical-middle students-list'>
            <td><%= c.course.name %></td>
            <td><%= c.student.name || c.student.account.number  %></td>
            <td><%= c.mark %></td>
            <td>
              <% $i = 0 %>
              <% $i += 1 if c.manner %>
              <% $i += 1 if c.level %>
              <% $i += 1 if c.pattern %>
              <% $i = 1 if $i == 0 %>
              <%= format("%0.2f",((c.manner || 0) + (c.level || 0) + (c.pattern || 0)).to_f / $i) %>分
				</td>
            <td><%= c.updated_at || c.created_at %></td>
            <td><%= link_to '详情', comment_path(c), class: ['btn btn-sm btn-primary']%></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <%= paginate @comments %>
</div>

app/views/teachercenter/course.html.erb
<p id="notice"><%= notice %></p>
<% if notice.nil? %>
  <button class='back btn btn-sm btn-primary' role='back'>Back</button>
<% else %>
  <button class='back btn btn-sm btn-primary' role='back double'>Back</button>
<% end %>
<div class='course-info fix-bounds'>
  <div class='info-box'>
    <div class='ico-box'>
      <%=  image_tag 'index/avatar.jpg', class: ['info-ico'] %>
      <br>
      <span class='label label-success'><%= set_course_stage @course.stage %></span>
    </div>
    <ul class='fix-ico-right'>
      <li class='fix-item'>
        <span>课程名：</span>
        <span><%= @course.name%></span>
      </li>
      <% if @course.is_public %>
        <li class='fix-item'>
          <span>报名人数：</span>
          <span><%= @course.students.length %></span>
        </li>
      <% else %>
        <li class='fix-item'>
          <span>学生：</span>
          <span>
            <% if @course.students.length != 0 %>
              <%= link_to @course.students[0].name || @course.students[0].account.number, student_path(@course.students[0]) %>
            <% end %>
          </span>
        </li>
      <% end %>
      <li class='fix-item'>
        <span>学科：</span>
        <span><%= @course.category %></span>
      </li>
      <li class='fix-item'>
        <span>地点:</span>
        <span><%= @course.place %></span>
      </li>
      <li class='fix-item'>
        <span>价格:</span>
        <span><%= @course.price %></span>
      </li>
      <li class='fix-item'>
        <span>课时数:</span>
        <span><%= @course.times %></span>
      </li>
      <li class='fix-item'>
        <span>上课时间:</span>
        <span><%= @course.class_time %></span>
      </li>
      <li class='fix-item'>
        <span>开班日期:</span>
        <span><%= @course.begintime %></span>
      </li>
      <li class='fix-item'>
        <span>课程评分:</span>
        <span><%= @course.score %></span>
      </li>
    </ul>
  </div>
  <% if @course.is_public %>
    <div class='fix-left info-box'>
      <span>报名学生：</span>
      <ul>
        <% @course.students.each do |s| %>
          <li class='item-list'><%= link_to s.name || s.account.number, student_path(s), class: 'btn btn-default' %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class='intro-box'>
    <div class='intro-head'>
      <span>课程介绍</span>
    </div>
    <div class='intro-content'>
      <span><%= @course.intro %></span>
    </div>
  </div>
</div>
<% if @course.stage == 'waiting' %>
  <%= form_tag '/teachercenter/dispose/course', method: :post, class: 'inline' do%>
    <%= hidden_field_tag 'command', 'refuse' %>
    <%= hidden_field_tag 'course_id', @course.id %>
    <%= submit_tag '拒绝预约', class: 'btn btn-danger' %>
  <% end %>
  <%= form_tag '/teachercenter/dispose/course', method: :post, class: 'inline' do%>
    <%= hidden_field_tag 'command', 'accept' %>
    <%= hidden_field_tag 'course_id', @course.id %>
    <%= submit_tag '接受预约', class: 'btn btn-primary' %>
  <% end %>
<% elsif @course.stage == 'ongoing' %>
  <%= form_tag '/teachercenter/dispose/course', method: :post, class: 'inline' do%>
    <%= hidden_field_tag 'command', 'finish' %>
    <%= hidden_field_tag 'course_id', @course.id %>
    <%= submit_tag '结束课程', class: 'btn btn-success' %>
  </br>
</br>
<P>
  <label class='label label-danger'>Tips:完成课程后学生才可进行评价</label>
</P>
<% end %>
<% elsif @course.stage == 'finished' %>
  <h4>课程评价</h4>
  <div class='info-box'>
    <table class='table'>
      <thead>
        <tr class='tr'>
          <td class='td'>学生</td>
          <td class='td'>评级</td>
          <td class='td'>综合评分</td>
          <td class='td'>评论时间</td>
          <td></td>
        </tr>
      </thead>
      <tbody class='collection'>
        <% if @course.comments.length == 0 %>
          <tr>
            <td>暂无评价</td>
          </tr>
        <% else %>
          <% @course.comments.each do |c| %>
            <tr class='vertical-middle students-list'>
              <td><%= c.student.name || c.student.account.number  %></td>
              <td><%= c.mark %></td>
              <td>
                <% $i = 0 %>
                <% $i += 1 if c.manner %>
                <% $i += 1 if c.level %>
                <% $i += 1 if c.pattern %>
                <% $i = 1 if $i == 0 %>
                <%= format("%0.2f",((c.manner || 0) + (c.level || 0) + (c.pattern || 0)).to_f / $i) %>分
		</td>
              <td><%= c.updated_at || c.created_at %></td>
              <td><%= link_to '详情', comment_path(c), class: ['btn btn-sm btn-primary']%></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/teachercenter/courses.html.erb
<%= render 'menu_tab' %>
<div class='courses_panel fix-bounds'>
  <div class='course_tab'>
    <ul id='course-tab' role="tablist">
      <li role="presentation" class="active">
        <a href="#all-courses" role="tab" data-toggle="tab">全部课程</a>
      </li>
      <li role="presentation">
        <a href='#private-courses' role="tab" data-toggle="tab">一对一</a>
      </li>
      <li role="presentation">
        <a href='#public-courses' role="tab" data-toggle="tab">公开课</a>
      </li>
    </ul>
    <div class='new-course'>
      <%= link_to teacenter_course_new_path do %>
        <span class='glyphicon glyphicon-plus-sign'></span>
        <p>新建课程</p>
      <% end %>
    </div>
  </div>
  <div class='tab-content course-content'>
    <% type = Array['all', 'true', 'false'] %>
    <% for t in type %>
      <div id='<%= set_ele_id(t) %>' class="tab-content tab-pane<%= ' active' if t == 'all' %>">
        <div class='fix-left courses-selection'>
          <div class='add-right-margin'>
            <span>筛选</span>
          </div>
          <ul role='courses-selection'>
            <li role="condition all" class="active">
              <a class='btn btn-sm btn-default' data-target="#all">全部</a>
            </li>
            <li role="condition">
              <a class='btn btn-sm btn-default' data-target='#ongoing'>进行中</a>
            </li>
            <li role="condition">
              <a class='btn btn-sm btn-default' data-target='#finished'>已结束</a>
            </li>
            <% if t != 'true'  %>
              <li role="condition">
                <a class='btn btn-sm btn-default' data-target="#waiting">待处理</a>
              </li>
              <li role="condition">
                <a class='btn btn-sm btn-default' data-target="#refused">已拒绝</a>
              </li>
            <% end %>
          </ul>
        </div>
        <table class='table'>
          <thead>
            <tr>
              <td>课程名</td>
              <td>学生姓名</td>
              <td>学科</td>
              <td>状态</td>
              <td><%= t %></td>
            </tr>
          </thead>
          <tbody>
            <% if !@courses.nil? %>
              <% @courses.each do |c| %>
                <% if (c.is_public.to_s == t || t == 'all') %>
                  <tr data-stage='<%= c.stage %>' data-public='<%= c.is_public %>' role="<%= 'all-courses' if t== 'all' %>">
                    <td><%= c.name %></td>
                    <td><% c.students.each do |s| %><%= s.name %><% end %></td>
                    <td><%= c.category %></td>
                    <td>
                      <span>
                        <% case c.stage %>
                        <% when 'waiting' %>
                        待处理
								<% when 'ongoing' %>
                        进行中
								<% when 'finished' %>
                        已结束
								<% when 'refused' %>
                        已拒绝
								<% end %>
                    </span>
                  </td>
                  <td><%= link_to '详情', teacenter_course_path(c), class: [:btn, 'btn-primary'] %></td>
                </tr>
              <% end %>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
</div>
<%= paginate @courses %>
</div>

app/views/teachercenter/index.html.erb
<%= render 'menu_tab' %>
<div class='user-info'>
  <div class='info-box'>
    <div class='ico-box'>
      <%=  image_tag 'index/avatar.jpg', class: ['info-ico'] %>
      <a href='#' class='btn btn-primary btn-sm'>更换</a>
    </div>
    <ul class='fix-ico-right'>
      <li class='fix-item'>
        <span>教师姓名：</span>
        <div role='info-cotent'>
          <em role='info' name='revise[name]' data-attr='name'><%= @teacher.name %></em>
          <input type='text-field' name='revise[name]' class='edit' role='edit'>
        </div>
        <div class='' role='revise-group'>
          <a class='revise' role='revise'>修改</a>
          <div class='control-group clearfix'>
            <a class='revise' role='cancel'>取消</a>
            <a class='revise' role='conform' data-target='teachercenter/revise'>确定</a>
          </div>
        </div>
      </li>
      <li class='fix-item'>
        <span>会员状态：</span>
        <% if @account.is_vip %>
          <span>已开通</span>
          <a href='#' class='state-ture'>续费会员</a>
        <% else %>
          <span>暂未开通</span>
          <a href='#' class='state-false'>立即开通VIP</a>
        <% end %>
      </li>
    </ul>
  </div>
  <div class='phone-email info-box'>
    <div class='phone'>
      <div class='ico-box'><img src='<%= %>' class='info-ico'></div>
      <ul class='fix-ico-right'>
        <li class='fix-item'>
          <% if @account.phone %>
            <p>手机已验证</p>
            <span><%= @account.phone %></span>
            <a href='#' class='state-ture'>修改手机号</a>
          <% else %>
            <p>手机未绑定</p>
            <a href='#' class='state-false'>立即绑定</a>
          <% end %>
        </li>
      </ul>
    </div>
    <div class='email'>
      <div class='ico-box'><img src='' class='info-ico'></div>
      <ul class='fix-ico-right'>
        <li class='fix-item'>
          <% if @account.email %>
            <p>邮箱已验证</p>
            <span><%= @account.email %></span>
            <a href='#' class='state-ture'>修改邮箱</a>
          <% else %>
            <p>邮箱未绑定</p>
            <a href='#' class='state-false'>立即绑定</a>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>
<div class='detail-info'>
  <ul>
    <li class='info-item'>
      <span>性别</span>
      <div role='info-cotent'>
        <em role='info' name='revise[sex]' data-attr='sex'><%= @teacher.sex %></em>
        <input type='text-field' name='revise[sex]' class='edit' role='edit'>
      </div>
      <div class='revise-group' role='revise-group'>
        <a class='revise' role='revise'>修改</a>
        <div class='control-group'>
          <a class='revise' role='cancel'>取消</a>
          <a class='revise' role='conform' data-target='teachercenter/revise'>确定</a>
        </div>
      </div>
    </li>
    <li class='info-item'>
      <span>生日</span>
      <div role='info-cotent'>
        <em role='info' data-attr='bornday'><%= @account.teacher.bornday %></em>
        <input type='date' name='revise[bornday]' role='edit' class='edit'>
      </div>
      <div class='revise-group' role='revise-group'>
        <a class='revise' role='revise'>修改</a>
        <div class='control-group'>
          <a class='revise' role='cancel'>取消</a>
          <a class='revise' role='conform' data-target='teachercenter/revise'>确定</a>
        </div>
      </div>
    </li>
    <li class='info-item'>
      <span>地址</span>
      <div role='info-cotent'>
        <em role='info' data-attr='address'><%= @account.teacher.address %></em>
        <input type='text-field' name='revise[address]' class='edit' role='edit'>
      </div>
      <div class='revise-group' role='revise-group'>
        <a class='revise' role='revise'>修改</a>
        <div class='control-group'>
          <a class='revise' role='cancel'>取消</a>
          <a class='revise' role='conform' data-target='teachercenter/revise'>确定</a>
        </div>
      </div>
    </li>
    <li class='info-item'>
      <span>学校</span>
      <div role='info-cotent'>
        <em role='info' data-attr='school'><%= @account.teacher.school %></em>
        <input type='text-field' name='revise[school]' class='edit' role='edit'>
      </div>
      <div class='revise-group' role='revise-group'>
        <a class='revise' role='revise'>修改</a>
        <div class='control-group'>
          <a class='revise' role='cancel'>取消</a>
          <a class='revise' role='conform' data-target='teachercenter/revise'>确定</a>
        </div>
      </div>
    </li>
  </ul>
</div>
<div class='intro-box detail-info'>
  <div class='intro-head'>
    <span>自我介绍</span>
  </div>
  <div class='intro-content'>
    <div class='revise-group' role='revise-group'>
      <a class='revise' role='revise'>修改</a>
      <div class='control-group'>
        <a class='revise' role='cancel'>取消</a>
        <a class='revise' role='conform' data-target='teachercenter/revise'>确定</a>
      </div>
    </div>
    <div role='info-cotent'>
      <em role='info' data-attr='intro'>
        <span><%= @account.teacher.intro %></span>
      </em>
      <textarea class='edit' name='revise[intro]' role='edit'><%= @account.student.intro %></textarea>
    </div>
  </div>
</div>

app/views/teachercenter/messages.html.erb
<%= render 'menu_tab' %>
<div class='info-box fix-bounds'>
  <table class='table'>
    <thead>
      <tr class='tr'>
        <td class='td'>标题</td>
        <td class='td'>来自</td>
        <td class='td'>状态</td>
        <td class='td'>接收时间</td>
      </tr>
    </thead>
    <tbody class='collection'>
      <% if !@messages.nil? %>
        <% @messages.each do |m| %>
          <tr class='vertical-middle students-list'>
            <td><%= m.title %></td>
            <td><%= m.sender %></td>
            <td><%= m.isread %></td>
            <td><%= m.updated_at.nil? ? m.updated_at.strftime("%Y-%m-%d") : m.created_at.strftime("%Y-%m-%d")  %></td>
            <td><%= link_to '详情', teacenter_messages_path(m), class: ['btn btn-sm btn-primary']%></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/teachercenter/new_course.html.erb
<div class='form-panel hidden' id='new-course-form'>
  <button class='back btn btn-sm btn-primary' role='back'>Back</button>
  <%= form_for @course, url: {action: "create_course"} do |f| %>
    <% if @course.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@course.errors.count, "error") %>
          prohibited this account from being saved:</h2>
        <ul>
          <% @course.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class='form-header'>
      <h2>请输入详细信息</h2>
    </div>
    <div class='form-body'>
      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :category %>
        <%= f.text_field :category %>
      </div>
      <div class="field">
        <%= f.label :price %>
        <%= f.text_field :price %>
      </div>
      <div class="field">
        <%= f.label :place %>
        <%= f.text_field :place %>
      </div>
    </div>
    <div class='form-footer'>
      <div class="actions">
        <button class='btn' type="submit">提交</button>
      </div>
    </div>
  <% end %>
</div>
<div class="modal fade" id="handbook-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <div class='handbook'>
          <div class='content'>
            <span>这是用户手册，请先阅读！</span>
          </div>
          <div class='control-group'>
            <div class='field'>
              <input type='checkbox' id='agree-btn'>
              <label for='agree-btn'>同意</label>
            </div>
            <button class="btn btn-danger" data-dismiss="modal" role="back">取消</button>
            <button class="btn btn-primary" id='conform-btn' disabled="disabled">确定</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>